kind: pipeline
name: maoxian-operator

steps:
  - name: golang build
    image: golang:1.13
    commands:
      - go build -o build/_output/bin/maoxian-operator cmd/manager/main.go
  - name: docker build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      dockerfile: build/Dockerfile
      repo: guoxudongdocker/maoxian-operator
      tags:
        - ${DRONE_BUILD_NUMBER}
        - v0.1.1