apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: maoxianbots.maoxian.guoxudong.io
spec:
  group: maoxian.guoxudong.io
  names:
    kind: MaoxianBot
    listKind: MaoxianBotList
    plural: maoxianbots
    singular: maoxianbot
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MaoxianBot is the Schema for the maoxianbots API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MaoxianBotSpec defines the desired state of MaoxianBot
          properties:
            plat:
              type: string
            repoList:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - plat
          - repoList
          type: object
        status:
          description: MaoxianBotStatus defines the observed state of MaoxianBot
          properties:
            repoStatus:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  error:
                    type: string
                  name:
                    type: string
                  status:
                    type: string
                  success:
                    type: boolean
                required:
                - name
                - status
                - success
                type: object
              type: array
          required:
          - repoStatus
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
